apiVersion: v1
kind: Namespace
metadata:
  name: vrobledo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab3-config
  namespace: vrobledo
data:
  USER_KEY: "vanessa"
---
apiVersion: v1
kind: Secret
metadata:
  name: lab3-secret
  namespace: vrobledo
type: Opaque
stringData:
  BD_PASSWORD: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-deployment
  namespace: vrobledo
  labels:
    app: lab3-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab3-app
  template:
    metadata:
      labels:
        app: lab3-app
    spec:
      containers:
      - name: lab3-container
        image: ghcr.io/vane-robledo/curso-devops-lab3:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
        - name: USER_KEY
          valueFrom:
            configMapKeyRef:
              name: lab3-config
              key: USER_KEY
        - name: BD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lab3-secret
              key: BD_PASSWORD
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: lab3-service
  namespace: vrobledo
  labels:
    app: lab3-app
spec:
  selector:
    app: lab3-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000